#pragma once

namespace DeviceBoard
{
    const char* xmlData =
        "<PERFORMANCES>"
        "<PERFORMANCE>"
        "<INFO>"
        "<NAME>Moogish</NAME>"
        "<TYPE>AnalogModeling</TYPE>"
        "<DESCRIPTION>"
        "<LINE1 text=\"Just a taste\" />"
        "<LINE2 text=\"of virtual...\" />"
        "</DESCRIPTION>"
        "</INFO>"
        "<POT_CONFIGURATION>"
        "<POT page=\"0\" id=\"1\" value=\"0\" name=\"CV3 Att\" />"
        "<POT page=\"0\" id=\"2\" value=\"0\" name=\"CV4 Att\" />"
        "<POT page=\"0\" id=\"3\" value=\"0\" name=\"CV5 Att\" />"
        "<POT page=\"0\" id=\"4\" value=\"0\" name=\"CV6 Att\" />"
        "<POT page=\"1\" id=\"1\" value=\"0\" name=\"Freq Coarse\" />"
        "<POT page=\"1\" id=\"2\" value=\"0\" name=\"Freq Fine\" />"
        "</POT_CONFIGURATION>"
        "<CV_INPUTS>"
        "</CV_INPUTS>"
        "</PERFORMANCE>"
        "<PERFORMANCE>"
        "<INFO>"
        "<NAME>PulsarHeaven</NAME>"
        "<TYPE>Pulsar Synthesis</TYPE>"
        "<DESCRIPTION>"
        "<LINE1 text=\"Pulses come &amp;\" />"
        "<LINE2 text=\"go do they...\" />"
        "</DESCRIPTION>"
        "</INFO>"
        "<POT_CONFIGURATION>"
        "<POT page=\"0\" id=\"1\" value=\"0\" name=\"CV3 Att\" />"
        "<POT page=\"0\" id=\"2\" value=\"0\" name=\"CV4 Att\" />"
        "<POT page=\"0\" id=\"3\" value=\"0\" name=\"CV5 Att\" />"
        "<POT page=\"0\" id=\"4\" value=\"0\" name=\"CV6 Att\" />"
        "<POT page=\"1\" id=\"1\" value=\"0\" name=\"Freq Coarse\" />"
        "<POT page=\"1\" id=\"2\" value=\"0\" name=\"Freq Fine\" />"
        "</POT_CONFIGURATION>"
        "<CV_INPUTS>"
        "</CV_INPUTS>"
        "</PERFORMANCE>"
        "<PERFORMANCE>"
        "<INFO>"
        "<NAME>SnowFlakes</NAME>"
        "<TYPE>FM</TYPE>"
        "<DESCRIPTION>"
        "<LINE1 text=\"Good old DX7\" />"
        "<LINE2 text=\"Where is he?\" />"
        "</DESCRIPTION>"
        "</INFO>"
        "<POT_CONFIGURATION>"
        "<POT page=\"0\" id=\"1\" value=\"0\" name=\"CV3 Att\" />"
        "<POT page=\"0\" id=\"2\" value=\"0\" name=\"CV4 Att\" />"
        "<POT page=\"0\" id=\"3\" value=\"0\" name=\"CV5 Att\" />"
        "<POT page=\"0\" id=\"4\" value=\"0\" name=\"CV6 Att\" />"
        "<POT page=\"1\" id=\"1\" value=\"0\" name=\"Freq Coarse\" />"
        "<POT page=\"1\" id=\"2\" value=\"0\" name=\"Freq Fine\" />"
        "</POT_CONFIGURATION>"
        "<CV_INPUTS>"
        "</CV_INPUTS>"
        "</PERFORMANCE>"
        "</PERFORMANCES>"
        ;

} // namespace DeviceBoard
